config/routes.rb
Rails.application.routes.draw do
  get 'answer', to: 'coaching#answer'

  get 'ask', to: 'coaching#ask'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController
  def answer
    @query = params[:query]
    @answer = "Something!"
  end

  def ask

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<div class="text-center">
  <h1><%= @query %></h1>
    <p>- You</p>

  <h1><%= @answer %></h1>
    <p>- Your Coach</p>

  <%= link_to "Ask a new question mofo", ask_path %>
</div>

app/views/coaching/ask.html.erb
<div class="container">
  <div class="row vertical-row-centered">
    <div class="col-xs-5 col-xs-offset-3">
      <form class="padding" action="answer">
        <label for="question">Speak to your coach</label>
        <input type="text" id="question" name="query" placeholder="what time is it?">
        <input class="btn btn-primary" type="submit" value="Go on!">
      </form>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>